### PR TITLE
Access restrictions

### LINKED ISSUE #50: access restrictions
Alternative to #13 

Eg. Require # of edits before using this tool? Require autoconfirmed?

### PR DESCRIPTION
**Pull request by zhuyifei1999**
autoconfirmed right + 50 edits on Commons 

Fixes #50

### CODE REVIEW

**Comment by zhuyifei1999** [comment]
Tested with my [test account](https://commons.wikimedia.org/w/index.php?title=User:Zhuyifei1999_(test)&redirect=no) with test tool: 
screenshot

**Comment by zhuyifei1999** [comment]
Deployed

**Comment by NahidSultan** [comment]
Thanks :) 
Hope it'll reduce the crap uploads.

**Comment by wilfredor** [comment]
Goodbye Bangladesh case

**Pull request merged**
