### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by wilfredor**

### CODE REVIEW

**Comment by zhuyifei1999** [comment]
JSHint says no.

Also, merge conflicts needs to be fixed.

**Comment by wilfredor** [comment]
Merge conflicts are fixed maybe, however, I can't test it because the
server show a 502 error. Could you help me to keep a python configuration
right?

 Thanks

2016-05-22 13:49 GMT-03:00 zhuyifei1999 <notifications@github.com>:

> JSHint says no.
>
> Also, merge conflicts needs to be fixed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Toollabs/video2commons/pull/35#issuecomment-220842744>
>



-- 
*Wilfredo Rodríguez*

**Comment by zhuyifei1999** [comment]
The keep video/audio & import subtitles options does not display.
Some whitespaces probably needs fixing.

**Comment by zhuyifei1999** [comment]
and deployed

**Pull request closed without merging**
